FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development

# Copy everything
COPY . .

WORKDIR /app/apps/web
EXPOSE 3000

# Mount the monorepo root and run Next.js in dev mode
CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
