FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development
# Install yarn globally
# RUN npm install -g yarn

# Copy root pack age files
COPY package.json yarn.lock turbo.json ./

# Install dependencies
# RUN yarn install --frozen-lockfile
COPY . .

WORKDIR /app/apps/web
EXPOSE 3000
# RUN ["yarn", "build"]
CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
# CMD ["yarn", "uuid"]