version: "3.8"

# Create a custom network with DNS configuration
networks:
  jam_network:
    driver: bridge

services:
  web:
    # for prod, change to apps/web/Dockerfile
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - NEXT_PUBLIC_PUBLIC_MINIO_ENDPOINT=s3.jam.local
      - NEXT_PUBLIC_PUBLIC_MINIO_PORT=80
      - NEXT_PUBLIC_PUBLIC_MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - PUBLIC_DOMAIN=jam.local
      - PUBLIC_S3_DOMAIN=s3.jam.local
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/:delegated
      - /app/node_modules
      - /app/storage
    # Add proper DNS resolution with extra_hosts
    extra_hosts:
      - "s3.jam.local:172.17.0.1"
      - "jam.local:172.17.0.1"
    depends_on:
      - nginx
      - minio
      - minio-init
    restart: unless-stopped
    networks:
      - jam_network
    # - postgres
    # - qdrant
    # - neo4j
    # - caldav
    # - embed-service
    # - summarization-service
    # - scheduler-service
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - jam_network
    # Define proper hostnames for the nginx container
    hostname: nginx
    extra_hosts:
      - "s3.jam.local:127.0.0.1"
      - "jam.local:127.0.0.1"
  
  minio:
    image: minio/minio
    ports:
      - "9090:9000"  # Only for direct access if needed
      - "9091:9001"  # Only for direct access if needed
    volumes:
      - ./storage/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_OPTS="--console-address :9001"
      # Tell MinIO that it's accessible via s3.jam.local
      - MINIO_SERVER_URL=http://s3.jam.local
      # Add custom domain for browser redirect
      - MINIO_BROWSER_REDIRECT_URL=http://console.s3.jam.local
    restart: unless-stopped
    command: server /data --console-address ":9001"
    networks:
      - jam_network
    hostname: minio
  
  #creates buckets in minio so they are available when the app starts
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        # wait until MinIO API is responsive
        until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        do echo 'Waiting for MinIO…' && sleep 2;
        done;
        # create your buckets if they don't already exist
        mc mb local/documents   || true;
        mc mb local/avatars     || true;
        mc mb local/notes-media || true;
        mc mb local/thumbnails  || true;
        mc mb local/temp        || true;

        echo 'Default buckets ensured';
      "
    # ensure it only runs once
    restart: "on-failure"
    networks:
      - jam_network
  # postgres:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_USER: nextai
  #     POSTGRES_PASSWORD: changeme
  #     POSTGRES_DB: nextai
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # qdrant:
  #   image: qdrant/qdrant:latest
  #   restart: always
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

  # neo4j:
  #   image: neo4j:4.4
  #   restart: always
  #   environment:
  #     NEO4J_AUTH: "neo4j/secret"
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - neo4j_data:/data

  # caldav:
  #   image: tomassedovic/radicale:latest
  #   restart: always
  #   ports:
  #     - "5232:5232"
  #   volumes:
  #     - caldav_data:/var/lib/radicale

  # embed-service:
  #   build:
  #     context: .
  #     dockerfile: packages/embed/Dockerfile
  #   restart: on-failure
  #   environment:
  #     DATABASE_URL: postgres://nextai:changeme@postgres:5432/nextai
  #     QDRANT_URL: http://qdrant:6333
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #   depends_on:
  #     - postgres
  #     - qdrant
  #   ports:
  #     - "5001:5001"

  # summarization-service:
  #   build:
  #     context: .
  #     dockerfile: packages/summarize/Dockerfile
  #   restart: on-failure
  #   environment:
  #     DATABASE_URL: postgres://nextai:changeme@postgres:5432/nextai
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5002:5002"

  # scheduler-service:
  #   build:
  #     context: .
  #     dockerfile: packages/scheduler/Dockerfile
  #   restart: on-failure
  #   environment:
  #     CALDAV_URL: http://caldav:5232
  #     CALDAV_USER: user
  #     CALDAV_PASSWORD: pass
  #   depends_on:
  #     - caldav
  #   ports:
  #     - "5003:5003"

# volumes:
  # postgres_data:
  # qdrant_data:
  # neo4j_data:
  # caldav_data:
